name: Deployment  

# on- runs the trigger
on: 
    pull_request:
     branches:
         - main


jobs: 
    test: 
     runs-on: ubuntu-latest
     container:
        image: node:24

     steps:
        - uses: actions/checkout@v4
        - run: npm ci
        - run: npm test
        - run: npm run build
